# Generated by Django 2.1.4 on 2018-12-10 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('program_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Program')),
                ('conference_field', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('api.program',),
        ),
        migrations.CreateModel(
            name='ConferenceTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Ticket')),
            ],
            bases=('api.ticket',),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('program_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Program')),
                ('exercise_field', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('api.program',),
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('program_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Program')),
                ('sprint_field', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('api.program',),
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('program_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Program')),
                ('tutorial_field', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('api.program',),
        ),
        migrations.CreateModel(
            name='Youngcoder',
            fields=[
                ('program_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Program')),
                ('youngcoder_field', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('api.program',),
        ),
        migrations.CreateModel(
            name='YoungcoderTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Ticket')),
                ('need_laptop', models.BooleanField(default=False)),
            ],
            bases=('api.ticket',),
        ),
        migrations.AddField(
            model_name='ticket',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Program'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
