# Generated by Django 2.1.4 on 2018-12-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_field',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='sprint_field',
        ),
        migrations.RemoveField(
            model_name='youngcoder',
            name='youngcoder_field',
        ),
    ]
