# Generated by Django 2.1.5 on 2019-02-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='presentation_proposal_finished_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='presentation_proposal_started_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='sprint_proposal_finished_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='sprint_proposal_started_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='tutorial_proposal_finished_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='tutorial_proposal_started_at',
            field=models.DateField(null=True),
        ),
    ]
