# Generated by Django 2.1.5 on 2019-02-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(null=True)),
                ('finished_at', models.DateField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='conference',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='started_at',
        ),
        migrations.AddField(
            model_name='conference',
            name='conference_finished_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='conference_started_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='sprint_finished_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='sprint_started_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='tutorial_finished_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='tutorial_started_at',
            field=models.DateField(null=True),
        ),
    ]
