# Generated by Django 2.1.4 on 2019-01-16 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20181210_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('program_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Program')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('api.program',),
        ),
        migrations.RemoveField(
            model_name='conference',
            name='program_ptr',
        ),
        migrations.DeleteModel(
            name='Conference',
        ),
    ]
