# Generated by Django 2.1.5 on 2019-02-16 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20190210_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, max_length=4000, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(db_index=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='profile')),
                ('avatar_url', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
