# Generated by Django 2.1.5 on 2019-03-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agreed',
            field=models.BooleanField(default=False),
        ),
    ]
