# Generated by Django 2.1.5 on 2019-03-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_agreed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='agreed',
        ),
    ]
