# Generated by Django 2.1.5 on 2019-02-16 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20190216_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, max_length=4000, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(db_index=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='profile')),
                ('avatar_url', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Ticket')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Conference')),
            ],
            bases=('api.ticket',),
        ),
        migrations.CreateModel(
            name='ProgramTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Ticket')),
            ],
            bases=('api.ticket',),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='YoungcoderTicket',
            fields=[
                ('programticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ProgramTicket')),
                ('need_laptop', models.BooleanField(default=False)),
            ],
            bases=('api.programticket',),
        ),
        migrations.AddField(
            model_name='programticket',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Program'),
        ),
    ]
