# Generated by Django 2.1.5 on 2019-03-16 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_profile_agreed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('detail_desc', models.TextField(blank=True, default='')),
                ('is_presented_before', models.BooleanField(default=False)),
                ('place_presented_before', models.CharField(blank=True, default='', max_length=255)),
                ('presented_slide_url_before', models.CharField(blank=True, default='', max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('coc_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('contents_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('etc_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('proposal_agreed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='is_presented_before',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='place_presented_before',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='presented_slide_url_before',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='question',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='short_desc',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='short_desc_en',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='short_desc_ko',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='submitted',
        ),
        migrations.AddField(
            model_name='presentationproposal',
            name='presentation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Presentation'),
        ),
    ]
