# Generated by Django 2.1.5 on 2019-02-17 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20190217_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(blank=True, max_length=255, null=True)),
                ('desc_ko', models.TextField(blank=True, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('desc_en', models.TextField(blank=True, null=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='sponsor')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(default=0)),
                ('ticket_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='sponsor',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SponsorLevel'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='ticket_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
