# Generated by Django 2.1.5 on 2019-03-16 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190316_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationproposal',
            name='presentation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='api.Presentation'),
        ),
    ]
