# Generated by Django 2.1.5 on 2019-03-16 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190316_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationproposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentationproposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
