# Generated by Django 2.1.5 on 2019-02-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190219_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthsetting',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='oauthsetting',
            name='env_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
