# Generated by Django 2.1.5 on 2019-02-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190220_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthsetting',
            name='env_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
