# Generated by Django 2.1.5 on 2019-02-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190221_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='earlybird_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='earlybird_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='presentation_proposal_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='presentation_proposal_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='sprint_proposal_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='sprint_proposal_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='tutorial_proposal_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='tutorial_proposal_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
