# Generated by Django 2.1.5 on 2019-04-02 16:01

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190402_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='owner',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='ticket_users',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='business_registration_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', upload_to='sponsor_business_registration'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='business_registration_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='contact_process_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='sponsor_logo'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='manager_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='manager_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='manager_phone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='manager_secondary_phone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SponsorLevel'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='후원금이 입금된 일시', null=True),
        ),
    ]
