# Generated by Django 2.1.5 on 2019-04-06 06:33

import api.models.sponsor
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190406_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='contact_process_required',
            new_name='contract_process_required',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='business_registration_image',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='business_registration_file',
            field=models.FileField(blank=True, default='', upload_to=api.models.sponsor.registration_file_upload_to),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo_vector',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=api.models.sponsor.logo_vector_upload_to),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='creator',
            field=models.ForeignKey(help_text='스폰서를 등록한 유저', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=api.models.sponsor.logo_image_upload_to),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(blank=True, help_text='스폰서 이름입니다. 서비스나 회사 이름이 될 수 있습니다.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name_en',
            field=models.CharField(blank=True, help_text='스폰서 이름입니다. 서비스나 회사 이름이 될 수 있습니다.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name_ko',
            field=models.CharField(blank=True, help_text='스폰서 이름입니다. 서비스나 회사 이름이 될 수 있습니다.', max_length=255, null=True),
        ),
    ]
