# Generated by Django 2.1.5 on 2019-02-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190225_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlevel',
            name='presentation_count',
            field=models.IntegerField(default=0),
        ),
    ]
