# Generated by Django 2.1.5 on 2019-02-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sponsorlevel_presentation_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlevel',
            name='limit',
            field=models.IntegerField(default=0),
        ),
    ]
