# Generated by Django 2.1.5 on 2019-04-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190406_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorlevel',
            name='ost_room_info',
        ),
        migrations.AddField(
            model_name='sponsorlevel',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
