# Generated by Django 2.1.5 on 2019-02-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_sponsorlevel_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorlevel',
            name='limit',
            field=models.IntegerField(default=0, help_text='스폰서 등급의 구좌수'),
        ),
        migrations.AlterField(
            model_name='sponsorlevel',
            name='presentation_count',
            field=models.IntegerField(default=0, help_text='스폰서에서 할 수 있는 스폰서 발표의 개수'),
        ),
        migrations.AlterField(
            model_name='sponsorlevel',
            name='ticket_count',
            field=models.IntegerField(default=0, help_text='스폰서에게 제공되는 티켓의 수'),
        ),
    ]
