# Generated by Django 2.1.5 on 2019-04-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190406_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorlevel',
            name='booth_size',
        ),
    ]
