# Generated by Django 2.1.5 on 2019-04-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_sponsorlevel_booth_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlevel',
            name='booth_info',
            field=models.CharField(blank=True, default='', help_text='후원사에게 제공되는 부스 정보', max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsorlevel',
            name='program_guide',
            field=models.CharField(blank=True, default='', help_text='프로그램 가이드에 후원사 소개가 수록되는 것에 대한 정보', max_length=100),
        ),
    ]
