# Generated by Django 2.1.5 on 2019-02-26 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190226_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
            preserve_default=False,
        ),
    ]
