# Generated by Django 2.1.5 on 2019-03-01 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190226_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio_en',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_ko',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name_en',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='name_ko',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
