# Generated by Django 2.2 on 2019-04-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190406_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='manager_email',
            field=models.CharField(blank=True, default='', help_text='후원사 담당자의 이메일 주소입니다.', max_length=100),
        ),
    ]
