# Generated by Django 2.2 on 2019-04-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190409_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='name_ko',
        ),
    ]
