# Generated by Django 2.2 on 2019-04-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_delete_youngcoderticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgramTicket',
        ),
    ]
