# Generated by Django 2.1.5 on 2019-03-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190301_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='oauth_type',
            field=models.CharField(choices=[('1', 'github'), ('2', 'google'), ('3', 'facebook'), ('4', 'naver')], default='1', max_length=1),
        ),
    ]
