# Generated by Django 2.2 on 2019-04-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyconKorea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('conference_start_at', models.DateField(blank=True, null=True)),
                ('conference_finish_at', models.DateField(blank=True, null=True)),
                ('tutorial_start_at', models.DateField(blank=True, null=True)),
                ('tutorial_finish_at', models.DateField(blank=True, null=True)),
                ('sprint_start_at', models.DateField(blank=True, null=True)),
                ('sprint_finish_at', models.DateField(blank=True, null=True)),
                ('keynote_recommendation_start_at', models.DateField(blank=True, null=True)),
                ('keynote_recommendation_finish_at', models.DateField(blank=True, null=True)),
                ('keynote_recommendation_announce_at', models.DateField(blank=True, null=True)),
                ('presentation_proposal_start_at', models.DateField(blank=True, null=True)),
                ('presentation_proposal_finish_at', models.DateField(blank=True, null=True)),
                ('presentation_review_start_at', models.DateField(blank=True, null=True)),
                ('presentation_review_finish_at', models.DateField(blank=True, null=True)),
                ('presentation_announce_at', models.DateField(blank=True, null=True)),
                ('tutorial_proposal_start_at', models.DateField(blank=True, null=True)),
                ('tutorial_proposal_finish_at', models.DateField(blank=True, null=True)),
                ('tutorial_proposal_announce_at', models.DateField(blank=True, null=True)),
                ('tutorial_ticket_start_at', models.DateField(blank=True, null=True)),
                ('tutorial_ticket_finish_at', models.DateField(blank=True, null=True)),
                ('sprint_proposal_start_at', models.DateField(blank=True, null=True)),
                ('sprint_proposal_finish_at', models.DateField(blank=True, null=True)),
                ('sprint_proposal_announce_at', models.DateField(blank=True, null=True)),
                ('sprint_ticket_start_at', models.DateField(blank=True, null=True)),
                ('sprint_ticket_finish_at', models.DateField(blank=True, null=True)),
                ('sponsor_proposal_start_at', models.DateField(blank=True, null=True)),
                ('sponsor_proposal_finish_at', models.DateField(blank=True, null=True)),
                ('volunteer_recruiting_start_at', models.DateField(blank=True, null=True)),
                ('volunteer_recruiting_finish_at', models.DateField(blank=True, null=True)),
                ('volunteer_announce_at', models.DateField(blank=True, null=True)),
                ('lightning_talk_proposal_start_at', models.DateField(blank=True, null=True)),
                ('lightning_talk_proposal_finish_at', models.DateField(blank=True, null=True)),
                ('lightning_talk_announce_at', models.DateField(blank=True, null=True)),
                ('earlybird_ticket_start_at', models.DateTimeField(blank=True, null=True)),
                ('earlybird_ticket_finish_at', models.DateTimeField(blank=True, null=True)),
                ('financial_aid_start_at', models.DateTimeField(blank=True, null=True)),
                ('financial_aid_finish_at', models.DateTimeField(blank=True, null=True)),
                ('financial_aid_announce_at', models.DateTimeField(blank=True, null=True)),
                ('patron_ticket_start_at', models.DateTimeField(blank=True, null=True)),
                ('patron_ticket_finish_at', models.DateTimeField(blank=True, null=True)),
                ('conference_ticket_start_at', models.DateTimeField(blank=True, null=True)),
                ('conference_ticket_finish_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Conference',
        ),
    ]
