# Generated by Django 2.1.5 on 2019-03-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20190305_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='background_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='duration',
            field=models.CharField(choices=[('S', '25'), ('L', '40')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='presentation',
            name='is_presented_before',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presentation',
            name='place_presented_before',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presentation',
            name='presented_slide_url_before',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
