# Generated by Django 2.2 on 2019-04-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20190412_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyconkorea',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pyconkorea',
            name='name_ko',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
