# Generated by Django 2.1.5 on 2019-03-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20190313_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='place_presented_before',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
