# Generated by Django 2.1.5 on 2019-03-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20190313_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='background_desc_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='background_desc_ko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='short_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='short_desc_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='short_desc_ko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='place_presented_before',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
