# Generated by Django 2.1.5 on 2019-03-13 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20190313_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='background_desc_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='background_desc_ko',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='short_desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='presentation',
            name='short_desc_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='short_desc_ko',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='background_desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='pdf_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='place_presented_before',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='presented_slide_url_before',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='question',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='slide_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='video_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='program',
            name='desc_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='desc_ko',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='program',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='program',
            name='name_ko',
            field=models.CharField(blank=True, default='', max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
