# Generated by Django 2.1.5 on 2019-03-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20190313_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='background_desc_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='background_desc_ko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='short_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='short_desc_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='short_desc_ko',
            field=models.TextField(blank=True, null=True),
        ),
    ]
