# Generated by Django 2.2 on 2019-04-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20190412_2352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PyconKorea',
            new_name='Schedule',
        ),
    ]
