# Generated by Django 2.2 on 2019-04-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20190414_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='contract_process_required',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='manager_phone',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='manager_secondary_phone',
        ),
    ]
