# Generated by Django 2.2 on 2019-04-25 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0033_auto_20190423_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyBirdTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imp_uid', models.CharField(blank=True, help_text='아이엠포트 uid입니다. 이 값은 환불 시에 사용됩니다.', max_length=255, null=True)),
                ('pg_tid', models.CharField(blank=True, help_text='PG사 Transaction ID입니다.', max_length=127, null=True)),
                ('receipt_url', models.CharField(blank=True, help_text='영수증 URL입니다. 이 값은 카드 결제 내역을 보여줄 때에 사용됩니다.', max_length=255, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
