# Generated by Django 2.2 on 2019-04-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0034_earlybirdticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('early_bird_ticket_cnt', models.IntegerField(default=100, help_text='판매할 얼리버드 컨퍼런스 티켓의 개수입니다.')),
                ('early_bird_ticket_price', models.IntegerField(default=0, help_text='얼리버드 컨퍼런스 티켓 가격입니다.')),
                ('conference_ticket_cnt', models.IntegerField(default=100, help_text='판매할 일반 컨퍼런스 티켓의 개수입니다.')),
                ('conference_ticket_price', models.IntegerField(default=0, help_text='일반 컨퍼런스 티켓 가격입니다.')),
            ],
        ),
    ]
