# Generated by Django 2.2 on 2019-04-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_init_ticketsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='earlybirdticket',
            name='is_refund',
            field=models.BooleanField(default=False, help_text='환불되었는지를 구분하는 필드입니다'),
        ),
    ]
