# Generated by Django 2.2 on 2019-04-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_program_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationproposal',
            name='coc_agreed_at',
        ),
        migrations.RemoveField(
            model_name='presentationproposal',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='presentationproposal',
            name='contents_agreed_at',
        ),
        migrations.RemoveField(
            model_name='presentationproposal',
            name='etc_agreed_at',
        ),
    ]
