# Generated by Django 2.2 on 2019-04-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20190427_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presentation',
            name='detail_desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='presentation',
            name='is_presented_before',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presentation',
            name='place_presented_before',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='presentation',
            name='presented_slide_url_before',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='presentation',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presentation',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
