# Generated by Django 2.2 on 2019-04-27 11:33

from django.db import migrations, models

def copy_proposal_field_to_presentation(apps, schema_editor):
    proposal_model = apps.get_model('api', 'PresentationProposal')
    for proposal in proposal_model.objects.all():
        proposal.presentation.detail_desc = proposal.detail_desc
        proposal.presentation.is_presented_before = proposal.is_presented_before
        proposal.presentation.place_presented_before = proposal.place_presented_before
        proposal.presentation.presented_slide_url_before = proposal.presented_slide_url_before
        proposal.presentation.accepted = proposal.accepted
        proposal.presentation.submitted = proposal.submitted
        proposal.presentation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20190427_2033'),
    ]

    operations = [
        migrations.RunPython(copy_proposal_field_to_presentation),
    ]
