# Generated by Django 2.2 on 2019-04-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_copy_proposal_field_to_presentation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PresentationProposal',
        ),
    ]
