# Generated by Django 2.2 on 2019-04-29 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0043_delete_presentationproposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_foreign', models.BooleanField(default=False)),
                ('amount', models.IntegerField(default=0, help_text='아이엠포트를 통해 결재한 가격입니다.')),
                ('imp_uid', models.CharField(blank=True, help_text='아이엠포트 uid입니다. 이 값은 환불 시에 사용됩니다.', max_length=255, null=True)),
                ('pg_tid', models.CharField(blank=True, help_text='PG사 Transaction ID입니다.', max_length=127, null=True)),
                ('receipt_url', models.CharField(blank=True, help_text='영수증 URL입니다. 이 값은 카드 결제 내역을 보여줄 때에 사용됩니다.', max_length=255, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('paid', 'Paid'), ('delete', 'Deleted'), ('cancelled', 'Cancelled')], default='ready', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=40)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', '컨퍼런스'), ('Y', '영코더'), ('B', '아이돌봄'), ('T', '튜토리얼'), ('S', '스프린트'), ('H', '체육시간')], default='C', max_length=1)),
                ('name', models.CharField(max_length=255, null=True)),
                ('name_ko', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('desc', models.TextField(blank=True, default='')),
                ('desc_ko', models.TextField(blank=True, default='', null=True)),
                ('desc_en', models.TextField(blank=True, default='', null=True)),
                ('start_at', models.DateTimeField(blank=True, help_text='행사가 시작되는 일시입니다.', null=True)),
                ('finish_at', models.DateTimeField(blank=True, help_text='행사가 종료되는 일시입니다.', null=True)),
                ('ticket_total', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('is_editable_price', models.BooleanField(default=False, help_text='개인후원과 같이 가격을 상향조정할 수 있는지 여부를 나타냅니다.')),
                ('is_unique_in_type', models.BooleanField(default=True, help_text='같은 타입간에 하나만 구매가 가능한지 여부를 나타냅니다. 대표적으로 컨퍼런스티켓이 이에 해당합니다.')),
                ('active', models.BooleanField(default=True, help_text='해당 티켓 판매가 활성화되었는지를 저장합니다. True이면 사용자에게 노출됩니다.')),
                ('cancelable_date', models.DateTimeField(blank=True, help_text='결재 취소가 가능한 기한입니다. 이 일시 이후에는 취소가 불가합니다.', null=True)),
                ('ticket_open_at', models.DateTimeField(blank=True, help_text='티켓 판매 시작 일시입니다.', null=True)),
                ('ticket_close_at', models.DateTimeField(blank=True, help_text='티켓 판매 종료 일시입니다.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='conferenceticket',
            name='owner',
        ),
        migrations.DeleteModel(
            name='TicketSetting',
        ),
        migrations.DeleteModel(
            name='ConferenceTicket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TicketProduct'),
        ),
    ]
