# Generated by Django 2.2 on 2019-04-29 10:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20190429_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='TicketOptions',
        ),
    ]
