# Generated by Django 2.2 on 2019-05-05 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_cfpreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfpreview',
            name='presentation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfp_review_set', to='api.Presentation'),
        ),
    ]
