# Generated by Django 2.2 on 2019-05-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20190505_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfpreview',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
