# Generated by Django 2.2 on 2019-05-12 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_cfpreview_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('B', 'BOOL'), ('N', 'NUMBER'), ('S', 'STRING')], default='S', max_length=1)),
                ('name', models.CharField(max_length=255, null=True)),
                ('desc', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TicketProduct')),
            ],
        ),
    ]
