# Generated by Django 2.2 on 2019-05-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20190512_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiondesc',
            name='desc_en',
            field=models.TextField(blank=True, default='', help_text='ticket 판매시 노출되는 설명입니다', null=True),
        ),
        migrations.AddField(
            model_name='optiondesc',
            name='desc_ko',
            field=models.TextField(blank=True, default='', help_text='ticket 판매시 노출되는 설명입니다', null=True),
        ),
        migrations.AddField(
            model_name='optiondesc',
            name='key',
            field=models.CharField(help_text='ticket에 저장되는 데이터의 KEY값입니다.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='optiondesc',
            name='name_en',
            field=models.CharField(help_text='ticket 판매시 노출되는 이름입니다', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='optiondesc',
            name='name_ko',
            field=models.CharField(help_text='ticket 판매시 노출되는 이름입니다', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='optiondesc',
            name='desc',
            field=models.TextField(blank=True, default='', help_text='ticket 판매시 노출되는 설명입니다'),
        ),
        migrations.AlterField(
            model_name='optiondesc',
            name='name',
            field=models.CharField(help_text='ticket 판매시 노출되는 이름입니다', max_length=255, null=True),
        ),
    ]
