# Generated by Django 2.2 on 2019-06-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20190620_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='is_keynote',
            field=models.BooleanField(default=False, help_text='키노트 스피커인 경우 TRUE로 설정합니다.'),
        ),
    ]
