# Generated by Django 2.2 on 2019-06-23 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_presentation_is_keynote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='babycare_ticket_finish_at',
            new_name='childcare_ticket_finish_at',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='babycare_ticket_start_at',
            new_name='childcare_ticket_start_at',
        ),
    ]
