# Generated by Django 2.2 on 2019-06-24 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0057_auto_20190623_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='secondary_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_owner_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
