# Generated by Django 2.2 on 2019-06-24 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='secondary_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_owner_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
