# Generated by Django 2.2 on 2019-06-26 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20190625_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='num_of_participants',
            field=models.IntegerField(default=0, help_text='수강 적절 인원 수 입니다.'),
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('program_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Program')),
                ('num_of_participants', models.IntegerField(default=0, help_text='수강 적절 인원 수 입니다.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('difficulty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Difficulty')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Place')),
            ],
            bases=('api.program',),
        ),
    ]
