# Generated by Django 2.2 on 2019-06-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20190626_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
