# Generated by Django 2.2 on 2019-06-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20190626_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
