# Generated by Django 2.2 on 2019-06-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_delete_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='desc2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='presentation',
            name='language2',
            field=models.CharField(choices=[('E', 'English'), ('K', 'Korean')], default='K', max_length=1),
        ),
        migrations.AddField(
            model_name='presentation',
            name='name2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='visible2',
            field=models.BooleanField(default=True),
        ),
    ]
