# Generated by Django 2.2 on 2019-07-05 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0019_fix_typoerror_of_tshirtsize'),
        ('api', '0065_delete_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='ticket_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.TicketProduct'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='ticket_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.TicketProduct'),
        ),
    ]
