# Generated by Django 2.2 on 2019-06-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20190628_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='desc2_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='desc2_ko',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='name2_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='name2_ko',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
