# Generated by Django 2.2 on 2019-07-07 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20190705_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='programming_language',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='ticket_product',
            field=models.ForeignKey(blank=True, help_text='프로그램과 연관된 티켓 제품입니다. action으로 자동 생성되는 필드이니 절대 수동으로 선택하지 말아주세요.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.TicketProduct'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='ticket_product',
            field=models.ForeignKey(blank=True, help_text='프로그램과 연관된 티켓 제품입니다. action으로 자동 생성되는 필드이니 절대 수동으로 선택하지 말아주세요.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.TicketProduct'),
        ),
    ]
