# Generated by Django 2.2 on 2019-07-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_youngcoder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youngcoder',
            name='recommend_age',
        ),
        migrations.RemoveField(
            model_name='youngcoder',
            name='recommend_age_en',
        ),
        migrations.RemoveField(
            model_name='youngcoder',
            name='recommend_age_ko',
        ),
        migrations.AddField(
            model_name='youngcoder',
            name='difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Difficulty'),
        ),
    ]
