# Generated by Django 2.2 on 2019-07-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_youngcoder_schedule_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='is_breaktime',
            field=models.BooleanField(default=False, help_text='쉬는 시간일 경우 TRUE로 설정합니다.'),
        ),
    ]
