# Generated by Django 2.2 on 2019-07-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_youngcoder_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-order', 'id']},
        ),
        migrations.AddField(
            model_name='program',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
