# Generated by Django 2.2 on 2019-08-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_lightningtalk'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightningtalk',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lightningtalk',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
