# Generated by Django 2.2 on 2019-08-08 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20190804_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='open_lunch_desc',
            field=models.TextField(blank=True, help_text='열린점심의 상세 설명입니다. 열린 점심을 하지 않는 후원사의 경우에는 공백으로 둡니다.', null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='open_lunch_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Place'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='open_lunch_title',
            field=models.CharField(blank=True, default='', help_text='열린점심 이름입니다. 홈페이지에 노출됩니다.', max_length=100),
        ),
    ]
