# Generated by Django 2.2 on 2019-08-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_auto_20190808_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightningtalk',
            name='materialLink',
            field=models.CharField(max_length=511, null=True),
        ),
    ]
