# Generated by Django 2.2 on 2019-08-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_lightningtalk_materiallink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightningtalk',
            old_name='materialLink',
            new_name='material_link',
        ),
    ]
