# Generated by Django 2.2 on 2019-08-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_remove_presentation_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='material_link',
        ),
    ]
