# Generated by Django 2.2 on 2019-08-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_remove_presentation_material_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightningtalk',
            old_name='material_link',
            new_name='slide_url',
        ),
        migrations.RemoveField(
            model_name='lightningtalk',
            name='material',
        ),
    ]
