# Generated by Django 2.2 on 2019-06-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ko', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, help_text='공지의 상세를 볼 수 있는 링크입니다. 주로 페이스북 링크가 들어가게 됩니다.', max_length=255, null=True)),
                ('active', models.BooleanField(default=True, help_text='True면 공지사항이 노출됩니다.')),
                ('published_at', models.DateTimeField(blank=True, help_text='공지가 노출된 일시입니다.', null=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
