# Generated by Django 2.2 on 2019-05-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiondesc',
            name='name',
            field=models.CharField(blank=True, default='', help_text='ticket 판매시 노출되는 이름입니다', max_length=255),
        ),
        migrations.AlterField(
            model_name='optiondesc',
            name='name_en',
            field=models.CharField(blank=True, default='', help_text='ticket 판매시 노출되는 이름입니다', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='optiondesc',
            name='name_ko',
            field=models.CharField(blank=True, default='', help_text='ticket 판매시 노출되는 이름입니다', max_length=255, null=True),
        ),
    ]
