# Generated by Django 2.2 on 2019-05-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20190513_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='merchant_uid',
            field=models.CharField(blank=True, default='', help_text='파이콘 한국에서 발행하는 주문번호입니다. 영수증에 출력됩니다.', max_length=100),
        ),
    ]
