# Generated by Django 2.2 on 2019-05-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_merchant_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_foreign',
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_domestic_card',
            field=models.BooleanField(default=True),
        ),
    ]
