# Generated by Django 2.2 on 2019-05-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20190513_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='cancelled_receipt_url',
            new_name='cancel_receipt_url',
        ),
    ]
