# Generated by Django 2.2 on 2019-05-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_auto_20190513_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cancel_receipt_url',
            field=models.CharField(blank=True, default='', help_text='결재 취소 영수증 URL입니다. 이 값은 카드 결제 취소 내역을 보여줄 때에 사용됩니다.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='receipt_url',
            field=models.CharField(blank=True, help_text='결재 영수증 URL입니다. 이 값은 카드 결제 내역을 보여줄 때에 사용됩니다.', max_length=255, null=True),
        ),
    ]
