# Generated by Django 2.2 on 2019-05-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20190513_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketproduct',
            name='warning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ticketproduct',
            name='warning_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='ticketproduct',
            name='warning_ko',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
