# Generated by Django 2.2 on 2019-05-22 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20190518_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketproduct',
            name='ticket_for',
            field=models.ManyToManyField(blank=True, help_text='티켓 판매되는 대상 유저들을 의미합니다. 만약 비어있을 경우 모든 유저에게 판매가 되며, 하나라도 유저가 지정되어 있으면 그 유저 외에는 볼 수 없습니다.', related_name='privileged_ticket_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
