# Generated by Django 2.2 on 2019-06-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_auto_20190610_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketproduct',
            name='is_deposit_ticket',
            field=models.BooleanField(default=False, help_text='단체 구매 등으로 티켓을 현금으로 입금하는 경우에 True로 설정합니다.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ready', 'ready'), ('deposit_waiting', 'deposit_waiting'), ('paid', 'paid'), ('cancelled', 'cancelled'), ('error', 'error')], default='ready', max_length=10),
        ),
    ]
