# Generated by Django 2.2 on 2019-06-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_auto_20190620_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ready', 'ready'), ('waiting', 'waiting'), ('paid', 'paid'), ('cancelled', 'cancelled'), ('error', 'error')], default='ready', max_length=10),
        ),
    ]
