# Generated by Django 2.2 on 2019-07-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_auto_20190620_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketproduct',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
