# Generated by Django 2.2 on 2019-07-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_ticketproduct_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketproduct',
            options={'ordering': ['-order', 'id']},
        ),
    ]
