# Generated by Django 2.2 on 2019-07-21 13:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0019_fix_typoerror_of_tshirtsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
    ]
