# Generated by Django 2.2 on 2019-08-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0020_auto_20190721_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
