# Generated by Django 2.2 on 2019-08-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0021_ticket_registered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketForRegistration',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ticket.ticket',),
        ),
    ]
