# Generated by Django 2.2 on 2019-08-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0022_ticketforregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketproduct',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketproduct',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticketproduct',
            name='name_ko',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
