# Generated by Django 2.2.2 on 2019-08-05 20:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0023_auto_20190805_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
