# Generated by Django 2.2 on 2019-08-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0024_auto_20190806_0501'),
        ('ticket', '0023_auto_20190812_1711'),
    ]

    operations = [
    ]
